steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/voice-assistant-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/voice-assistant-backend:latest'
      - '.'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/voice-assistant-backend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/voice-assistant-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: 1200s

images:
  - 'gcr.io/$PROJECT_ID/voice-assistant-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/voice-assistant-backend:latest'