steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/voice-assistant-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/voice-assistant-backend:latest'
      - '.'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/voice-assistant-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/voice-assistant-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'voice-assistant-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/voice-assistant-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '100'
      - '--timeout'
      - '900'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'JWT_SECRET=JWT_SECRET:latest'
      - '--set-secrets'
      - 'OPENAI_API_KEY=OPENAI_API_KEY:latest'
      - '--set-secrets'
      - 'GOOGLE_CLOUD_PROJECT_ID=GOOGLE_CLOUD_PROJECT_ID:latest'
      - '--set-secrets'
      - 'AIRTABLE_API_KEY=AIRTABLE_API_KEY:latest'
      - '--vpc-connector'
      - 'voice-assistant-vpc-connector'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: 1200s

images:
  - 'gcr.io/$PROJECT_ID/voice-assistant-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/voice-assistant-backend:latest'